version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always # Will restart if there is any failure
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch # Creates a dependency on the elasticsearch docker in case of restarting
volumes:
  elasticsearch-data:
    driver: local # Means is going to store the volume local in the PC.

# Running cmd: docker-compose -f elasticsearch-kibana.yml up -d